version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: flight_booking_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flight_db
    ports:
      - "3306:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
